#pragma once
#include "RPG2D/Core/Application.h"
#include "RPG2D/Core/LogSystem.h"
#include "RPG2D/Core/Layer.h"
#include "RPG2D/Core/Timestep.h"
#include "RPG2D/ImGui/ImGuiLayer.h"
#include "RPG2D/Function/Global/GlobalContext.h"
#include "RPG2D/Function/Script/Components.h"
#include "RPG2D/Function/Script/Entity.h"
#include "RPG2D/Resource/Scene/Scene.h"
//entry point
#include "RPG2D/Core/EntryPoint.h"