#pragma once
#include "RPG2D/Core/Application.h"
#include "RPG2D/Core/LogSystem.h"
#include "RPG2D/Core/Timestep.h"
#include "RPG2D/Function/Global/GlobalContext.h"
#include "RPG2D/Resource/ResType/Components.h"
//#include "RPG2D/Events/Event.h"
#include "RPG2D/Resource/ResType/Entity.h"
#include "RPG2D/Resource/Scene/Scene.h"
#include "RPG2D/Resource/ResType/ScriptableEntity.h"
//entry point